### ISSUE TITLE
unit test detected use of eval in tools/docsite/Doc.py

### ISSUE THREAD

**Issue by delandtj** [threefoldtech/jumpscale_lib#117]
really *really* must not use eval.

```
======================================================================
ERROR: test0032_j_tools_docsites_test (tests.jumpscale_test.test09_js_dynamic_walker.TestJSDynamicWalkerTestSearch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lkcl/src/lib9/JumpscaleLib/tools/docsite/Doc.py", line 290, in _macros_process
    macro = eval(cmd) #is the result of the macro which is returned
  File "<string>", line 1, in <module>
```

**Comment by delandtj** [comment]
```
## ERROR: links

- in doc: doc:links:/opt/code/github/threefoldtech/jumpscale_weblibs/docsites_examples/test/blog/Links.md

**ERROR:** problem with link:[something]("include_test.md")
found unsupported extension



[]
link:link:https://unsplash.com/
link:image:unsplash.jpeg
link:image:balance_inspiration_motivation_life_scene_wander_big.jpg
link:image:piggy_bank_400.png
link:image:piggy_bank_401.png
link:link:http://farming_slides.threefold.me
link:link:https://docs.google.com/presentation/d/11FE7i7DkBO39pYzPpIp_mdafiHdPUMuWN0BoIM0KFjc/edit?usp=drive_web&ouid=101460153806293923139
link:doc:include_test
link:doc:include_test.md
link::include_test.md
```python
ERROR IN MACRO*** TODO: *1 ***
cmd:
j.tools.docsites.macros.include(self,"test5",content=block)
ERROR:
'DocSites' object has no attribute 'macros'
```

```
