### ISSUE TITLE
zbundle fails with internal error during start

### ISSUE THREAD

**Issue by dmitrydelyukin** [threefoldtech/jumpscale_lib#148]
[Mon24 07:16] - PrefabCore.py     :1123:j.prefabcore         - INFO     - RUN:smartctl --version
[Mon24 07:16] - PrefabSmartmontools.py:27  :j.prefabsmartmontools - INFO     - smartctl version 6.6 is present
Traceback (most recent call last):
  File "/etc/register_capacity.py", line 15, in <module>
    _, resp = client.api.RegisterCapacity(data)
  File "//lib/python/JumpScale9Lib/clients/grid_capacity/api_service.py", line 167, in RegisterCapacity
    resp = self.client.post(uri, data, headers, query_params, content_type)
  File "//lib/python/JumpScale9Lib/clients/grid_capacity/http_client.py", line 62, in post
    return self._handle_data(uri, data, headers, params, content_type, self.session.post)
  File "//lib/python/JumpScale9Lib/clients/grid_capacity/http_client.py", line 58, in _handle_data
    res.raise_for_status()
  File "//lib/python/requests/models.py", line 937, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://capacity.threefoldtoken.com/api/nodes
[Mon24 07:19] - ErrorHandler.py   :257 :j.core.errorhandler  - ERROR    - 500 Server Error: Internal Server Error for url: https://capacity.threefoldtoken.com/api/nod

**Comment by maxux** [comment]
Please use `https://hub.grid.tf/maxux/fullcapacity.flist` flist on zbundle to register capacity and tell me if it's fixed or not for you.

**Comment by rkhamis** [comment]
@maxux shouldn't we promote this flist?

**Comment by maxux** [comment]
If we confirm it works, yes

**Comment by zaibon** [comment]
@dmitrydelyukin please download the lastest zbundle build from : https://download.gig.tech/gig-autobuilder/threefoldtech-0-bundle-master-67a2042cce.tar.gz
extract the binary from there and run it with this flist: https://hub.grid.tf/maxux/fullcapacity.flist

that should do the trick.
We'll have to clean up a bit our doc to make sure we point to the proper zbundle build

**Comment by dmitrydelyukin** [comment]
---
/etc/start: line 4: /env.sh: No such file or directory
Generating public/private rsa key pair.
/root/.ssh/id_rsa already exists.
Overwrite (y/n)? /etc/start: line 10: js_config: command not found
registring farmer with ID:
Traceback (most recent call last):
  File "/etc/register_capacity.py", line 1, in <module>
    from jumpscale import j
  File "/usr/lib/python3/dist-packages/jumpscale.py", line 2, in <module>
    from Jumpscale.core.JSBase import JSBase
ImportError: No module named 'Jumpscale'

**Comment by abdulgig** [comment]
> 
> 
> @dmitrydelyukin please download the lastest zbundle build from : https://download.gig.tech/gig-autobuilder/threefoldtech-0-bundle-master-67a2042cce.tar.gz
> extract the binary from there and run it with this flist: https://hub.grid.tf/maxux/fullcapacity.flist
> 
> that should do the trick.
> We'll have to clean up a bit our doc to make sure we point to the proper zbundle build

Was testing the Zbundle, but there are DNS errors all over. Not sure if the Zbundle uses a custom DNS,

```+---[RSA 2048]----+
|                 |
|                 |
|       o         |
|  . o =.o        |
|   + O.ES        |
|    X.O.o o      |
|.o *.B . *       |
|o.o+O.oo+ o      |
|+.oO*o+.o=       |
+----[SHA256]-----+
[Sun21 12:41] - LoggerFactory.py  :236 :logger               - DEBUG    - start re-init for logging
* Will start agent
 9201 ?        Ss     0:00 ssh-agent -a /tmp/ssh-glVPrp66uk3V/agent.1654
12091 ?        S+     0:00 /bin/bash -c ps ax | grep 'ssh-agent'
12093 ?        S+     0:00 grep ssh-agent

* load ssh agent
* load ssh key: /root/.ssh/id_rsa
Identity added: /root/.ssh/id_rsa (/root/.ssh/id_rsa)
Lifetime set to 86400 seconds

registring farmer with ID: eyJhbGciOiJFUzM4NCIsInR5cCI6IkpXVCJ9.eyJhenAiOiJ0aHJlZWZvbGQuZmFybWVycyIsImV4cCI6MTUzMjUwNzUwMywiaXNzIjoiaXRzeW91b25saW5lIiwicmVmcmVzaF90b2tlbiI6IlRORFJoWkhNNHZMR
lJHcFprLVVvZWdabnRkMjEiLCJzY29wZSI6WyJ1c2VyOm1lbWJlcm9mOm1henJhYSJdLCJ1c2VybmFtZSI6ImFyZWhtYW4ifQ.j-
[Sun21 12:41] - capacity_parser.py:61  :pacity.capacity_parser - ERROR    - error fetch location: HTTPSConnectionPool(host='geoip-db.com', port=443): Max retries exceeded with url: /json (C
aused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fc1c68d0c50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:
```

**Comment by dmitrydelyukin** [comment]
any workaround/solution? do I need to change something in config?

**Comment by maxux** [comment]
New image is coming

**Comment by maxux** [comment]
Please try again my flist: https://hub.grid.tf/maxux/fullcapacity.flist

**Comment by abdulgig** [comment]
Seems to be working now ! The node gets registered and shows on the portal

```
10670 ?        S+     0:00 /bin/bash -c ps ax | grep 'ssh-agent'
10672 ?        S+     0:00 grep ssh-agent

* load ssh agent
* load ssh key: /root/.ssh/id_rsa
Identity added: /root/.ssh/id_rsa (/root/.ssh/id_rsa)

registring farmer with ID: eyJhbGciOiJFUzM4NCIsInR5cCI6IkpXVCJ9.eyJhenAiOiJ0aHJlZWZvbGQuZmFybWVycyIsImV4cCI6MTUzMjUwNzUwMywiaXNzIjoiaXRzeW91b25saW5lIiwicmVmcmVzaF90b2tlbiI6IlRORFJoWkhNNHZMRlJHcFprLVVvZWdabnRkMjEiLCJzY29wZSI6WyJ1c2VyOm1lbWJlcm9mOm1henJhYSJdLCJ1c2VybmFtZSI6ImFyZWhtYW4ifQ.j-

[Tue23 06:31] - register_capacity.py:19  :j.zbundle_capacity   - INFO     - capacity registered

```

**Comment by zaibon** [comment]
@abdulgig ok cool, we will promote the flist and update our doc, but happy that you are unblocked

**Comment by dmitrydelyukin** [comment]
can't start zbundle.
same error

/etc/start: line 4: /env.sh: No such file or directory
Generating public/private rsa key pair.
/root/.ssh/id_rsa already exists.
Overwrite (y/n)? /etc/start: line 10: js_config: command not found
registring farmer with ID:
Traceback (most recent call last):
  File "/etc/register_capacity.py", line 1, in <module>
    from jumpscale import j
  File "/usr/lib/python3/dist-packages/jumpscale.py", line 2, in <module>
    from Jumpscale.core.JSBase import JSBase
ImportError: No module named 'Jumpscale'

**Comment by zaibon** [comment]
@dmitrydelyukin which flist are these logs coming from ?

**Comment by dmitrydelyukin** [comment]
I use https://hub.grid.tf/maxux/fullcapacity.flist

do I need to create new organisation and get new farmer id?

**Comment by muhamadazmy** [comment]
Can u make sure u remove all working folders of `zbundle` 

try
```bash
rm -rf ~/.zbundle*
```

Then try again

**Comment by zaibon** [comment]
Seems @dmitrydelyukin  still have issue with the flist:
```
Reading package lists...
Building dependency tree...
Reading state information...
redis-server is already the newest version (2:3.0.6-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
vm.overcommit_memory = 1
Traceback (most recent call last):
  File "/etc/register_capacity.py", line 17, in <module>
    _, resp = client.api.RegisterCapacity(data)
  File "/opt/code/github/threefoldtech/jumpscale_lib/JumpscaleLib/clients/threefold_directory/api_service.py", line 167, in RegisterCapacity
    resp = self.client.post(uri, data, headers, query_params, content_type)
  File "/opt/code/github/threefoldtech/jumpscale_lib/JumpscaleLib/clients/threefold_directory/http_client.py", line 62, in post
    return self._handle_data(uri, data, headers, params, content_type, self.session.post)
  File "/opt/code/github/threefoldtech/jumpscale_lib/JumpscaleLib/clients/threefold_directory/http_client.py", line 58, in _handle_data
    res.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://capacity.threefoldtoken.com/api/nodes
[Tue20 08:54] - RedisFactory.py   :230 :j.clients.redis      - INFO     - redis-server --port 6379 --unixsocket /tmp/redis.sock --maxmemory 100000000 --daemonize yes
[Tue20 08:54] - Jinja2.py         :40  :j.tools.jinja2       - DEBUG    - template render:/opt/code/github/threefoldtech/digital_me/DigitalMeLib/data/schema//templates/template_obj.py
[Tue20 08:54] - Jinja2.py         :40  :j.tools.jinja2       - DEBUG    - template render:/opt/code/github/threefoldtech/digital_me/DigitalMeLib/data/schema//templates/schema.capnp
```

**Comment by maxux** [comment]
@dmitrydelyukin can you retry with the same flist, it was updated right now.
If everything is okay for you, I'll promote it.

**Comment by maxux** [comment]
This document was updated:
https://github.com/threefoldtech/home/blob/master/docs/farmers/zbundle.md

The flist was promoted. Please everybody confirm this can be closed.
