### ISSUE TITLE
Support atomicswap for the Btc electrum client

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/jumpscale_lib#27]
*Issue migrated from [https://api.github.com/repos/Jumpscale/lib9/issues/340](), opened by @ahussein*

One we have a the electrum wallet ready [#339] we will need to investigate how to support atomicswap operations similar to the Rivine client.

Rivine team already have atomicswap support for electrum wallet that can be used as [a reference](https://github.com/rivine/atomicswap)

**Comment by rkhamis** [comment]
*commented by @despiegk
we will migrate lots of code from the jimber team*

**Comment by rkhamis** [comment]
*commented by @ahussein
These tickets part of https://docs.greenitglobe.com/gig/org_development/issues/91 were created after dicussions with the jimber people. This means that they do not have a corresponding implementation to to what this ticket is supposed to do.

Right now, jimber does not support atomicswap via light wallets and this ticket is a step toward that. *

**Comment by ahussein** [comment]
why this is closed ?

**Comment by robvanmieghem** [comment]
Currently there is a Go implementation at https://github.com/rivine/atomicswap
We need to see how bewst to provide this functionality in jumpscale

**Comment by ahussein** [comment]
I have been able to move forward from the above issue, I have implemented a new Module ElectrumAtomicswap that should support the atomicswap operations on btc electrum network (now it supports initiate step).

The issue I am facing now is that the btcatomicswap command is interactive and we need to run it in non-interactive mood to be able to automate the process.

code can be found under branch electrum_atomicswap

**Comment by robvanmieghem** [comment]
I'll port the code the Jimber guys did on the original btcatomicswap code.

**Comment by ahussein** [comment]
Changes are both on development and development_simple branches.
I cannot get a working installation of js on development_simple to check the if porting the changes works fine.

I will put this ticket on verification, noting that i only tested it on development branch.

**Comment by siddiquagig** [comment]
Verifying on development_simple using this doc [https://github.com/threefoldtech/jumpscale_lib/blob/development_simple/docs/clients/blockchain/atomicswapwalkthrough.md](url)
- While executing```j.tools.prefab.local.blockchain.electrum.install(reset=True)``` got this error:

```
/opt/code/github/threefoldtech/jumpscale_core/Jumpscale/tools/executor/ExecutorLocal.py in execute(self, cmds, die, checkok, showout, timeout, env, sudo)
    114
    115         rc, out, err = j.sal.process.execute(
--> 116             cmds2, die=die, showout=showout, timeout=timeout)
    117
    118         if checkok:

/opt/code/github/threefoldtech/jumpscale_core/Jumpscale/sal/process/SystemProcess.py in execute(self, command, showout, useShell, log, cwd, timeout, errors, ok, captureout, die, async_, env)
    208                 msg+="stderr:\n"
    209                 msg+= j.core.text.indent(err).rstrip()+"\n\n"
--> 210             raise RuntimeError(msg)
    211
    212         # close the files (otherwise resources get lost),

RuntimeError:
Could not execute:    set -e
    [ ! -e '/root/.bash_profile' ] && touch '/root/.bash_profile'
    source /root/.bash_profile
    cp -v /tmp/k4qt4l7s8h/electrum/electrum /root/opt/bin/

stdout:
    '/tmp/k4qt4l7s8h/electrum/electrum' -> '/root/opt/bin/'

stderr:
    cp: cannot create regular file '/root/opt/bin/': No such file or directory

```

Manually created the required dir, but this needs to be in the installer script.


After this:

Configure and start Electrum as a daemon :
```
[6]: j.tools.prefab.local.blockchain.electrum.start(rpcuser='user', rpcpass='pass', rpcport=7777, rpchost='localhost', testnet=True)


RuntimeError:
Could not execute:    set -e
    [ ! -e '/root/.bash_profile' ] && touch '/root/.bash_profile'
    source /root/.bash_profile
    electrum --testnet -D /root/opt/var/data/electrum setconfig rpcuser user

stderr:
    [ecc] warning: libsecp256k1 library not available, falling back to python-ecdsa
    Traceback (most recent call last):
      File "/root/opt/bin/electrum", line 397, in <module>
        config = SimpleConfig(config_options)
      File "/usr/local/lib/python3.6/dist-packages/electrum/simple_config.py", line 85, in __init__
        self.path = self.electrum_path()
      File "/usr/local/lib/python3.6/dist-packages/electrum/simple_config.py", line 109, in electrum_path
        make_dir(path, allow_symlink=False)
      File "/usr/local/lib/python3.6/dist-packages/electrum/util.py", line 897, in make_dir
        os.mkdir(path)
    FileNotFoundError: [Errno 2] No such file or directory: '/root/opt/var/data/electrum'

```

Again manually created the required dir.


-Generate seed and give the required parameters:
```
In [7]: seed = j.clients.btc_electrum.generate_seed(256)

In [8]: data_dir = '/root/opt/var/data/electrum'
   ...: rpcuser = 'user'
   ...: rpcpass = 'pass'
   ...: rpcport = 7777
   ...: rpchost= 'localhost'
   ...: wallet_name = 'mybtcwallet'

In [9]: client_data = {
   ...:   'server': "{}:{}:s".format(rpchost, rpcport),
   ...:   'rpc_user': rpcuser,
   ...:   'rpc_pass_': rpcpass,
   ...:   'seed_': seed,
   ...:   'password_': "",
   ...:   "passphrase_": "",
   ...:   "electrum_path": data_dir,
   ...:   "testnet": 1
   ...: }
```

Now when executing ```electrum_cl = j.clients.btc_electrum.get(instance=wallet_name,data=client_data)``` got this error:

```
In [10]: electrum_cl = j.clients.btc_electrum.get(instance=wallet_name,data=client_data)
    ...:
[Tue02 14:53] - ConfigManager.py  :404 :gmanager.configmanager - INFO     - found 0 keys from ssh-agent
[Tue02 14:53] - SSHKeys.py        :153 :j.clients.sshkey     - INFO     - Will start agent
[Tue02 14:53] - SSHKeys.py        :274 :j.clients.sshkey     - INFO     - load ssh agent
[Tue02 14:53] - SSHKeys.py        :79  :j.clients.sshkey     - INFO     - load ssh key: /root/.ssh/id_rsa
[Tue02 14:53] - ConfigManager.py  :384 :gmanager.configmanager - INFO     - Jumpscale init: ssh key found in agent is:'/root/.ssh/id_rsa'
[Tue02 14:53] - ConfigManager.py  :384 :gmanager.configmanager - INFO     - Jumpscale init: Is it ok to use this one:'/root/.ssh/id_rsa'?
 [y/n]: y



/opt/code/github/threefoldtech/jumpscale_core/Jumpscale/sal/fs/SystemFS.py in listDirsInDir(self, path, recursive, dirNameOnly, findDirectorySymlinks, followSymlinks)
    850             path, str(recursive)))
    851
--> 852         items = self._listInDir(path)
    853         filesreturn = []
    854         for item in items:

/opt/code/github/threefoldtech/jumpscale_core/Jumpscale/sal/fs/SystemFS.py in _listInDir(self, path, followSymlinks)
    671         @param path: string (Directory path to list contents under)
    672         """
--> 673         names = os.listdir(path)
    674         return names
    675

FileNotFoundError: [Errno 2] No such file or directory: '/root/code'
```

After making this dir, another error:

```
In [11]: electrum_cl = j.clients.btc_electrum.get(instance=wallet_name,data=client_data)

/opt/code/github/threefoldtech/jumpscale_core/Jumpscale/tools/configmanager/ConfigManager.py in init(self, data, silent, configpath, keypath)
    487             if configpath == "":
    488                 # means config directory not configured
--> 489                 configpath, giturl = self._findConfigRepo(die=False)
    490
    491                 if silent:

/opt/code/github/threefoldtech/jumpscale_core/Jumpscale/tools/configmanager/ConfigManager.py in _findConfigRepo(self, die)
    188             return path, None
    189         paths = []
--> 190         for key, path in j.clients.git.getGitReposListLocal().items():
    191             if j.sal.fs.exists(j.sal.fs.joinPaths(path, ".jsconfig")):
    192                 paths.append(path)

/opt/code/github/threefoldtech/jumpscale_core/Jumpscale/clients/git/GitFactory.py in getGitReposListLocal(self, provider, account, name, errorIfNone)
    831             raise RuntimeError(
    832                 "Cannot find git repo for search criteria provider:'%s' account:'%s' name:'%s'" %
--> 833                 (provider, account, name))
    834         return repos
    835

RuntimeError: Cannot find git repo for search criteria provider:'' account:'' name:''

```
Reference ticket needs to be checked first in order to resolve issues in development_simple
#156
