### ISSUE TITLE
Improve zeroboot client parsing

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/jumpscale_lib#3]
Detailed description

Currently the zero boot client parses the host configuration using a specific order (ip, mac, name). This should be more flexible to allow different orders in the uci configuration in case of configuration not added through the client.

See code: https://github.com/Jumpscale/lib9/blob/development/JumpScale9Lib/clients/zeroboot/ZerobootClient.py#L306

**Comment by rkhamis** [comment]
Please fix here: https://github.com/threefoldtech/jumpscale_lib/blob/development/JumpscaleLib/clients/zero_boot/ZerobootClient.py#L306

**Comment by islamTaha12** [comment]
```bash
In [27]: host['zb_ipmi_host']
Out[27]: robot://zero-boot/github.com/zero-os/0-boot-templates/zeroboot_ipmi_host/0.0.1?guid=ba9e6b24-eb3b-4042-a0d0-5036cbcf0294&name=ipmi-storage03_ipmi_host

In [28]: host = host['zb_ipmi_host']

In [29]: task = host.schedule_action('install')

In [30]: task.wait(die=True)
Traceback (most recent call last):
  File "/opt/code/github/zero-os/0-robot/zerorobot/task/task.py", line 79, in execute
    self._result = self._func()
  File "/opt/code/github/zero-os/0-boot-templates/templates/zeroboot_ipmi_host/zeroboot_ipmi_host.py", line 76, in install
    if self.data['hostname'] in self._network.hosts.list():
  File "/opt/code/github/zero-os/0-boot-templates/templates/zeroboot_ipmi_host/zeroboot_ipmi_host.py", line 35, in _network
    self.___network = self._zeroboot.networks.get(self.data['network'])
  File "/opt/code/github/zero-os/0-boot-templates/templates/zeroboot_ipmi_host/zeroboot_ipmi_host.py", line 25, in _zeroboot
    return j.clients.zboot.get(self.data['zerobootClient'], interactive=False)
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/configmanager/JSBaseClassConfigs.py", line 43, in get
    return self._child_class(instance=instance, data=data, parent=self, interactive=interactive,**kwargs)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/zeroboot/ZerobootClient.py", line 47, in __init__
    self.networks = Networks(self.sshclient)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/zeroboot/ZerobootClient.py", line 146, in __init__
    self._populate()
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/zeroboot/ZerobootClient.py", line 167, in _populate
    self._networks[subnet] = Network(subnet, self.sshclient, networkname=networkname)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/zeroboot/ZerobootClient.py", line 109, in __init__
    self.hosts = Hosts(self.sshclient, self.subnet, self.leasetime, networkname=networkname)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/zeroboot/ZerobootClient.py", line 285, in __init__
    self._populate()
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/zeroboot/ZerobootClient.py", line 312, in _populate
    if netaddr.IPAddress(ip) in netaddr.IPNetwork(self.subnet):
  File "/usr/local/lib/python3.5/dist-packages/netaddr/ip/__init__.py", line 306, in __init__
    'address from %r' % addr)
netaddr.core.AddrFormatError: failed to detect a valid IP address from 'cluster01'
---------------------------------------------------------------------------
ErrorConditionObject                      Traceback (most recent call last)
/usr/local/bin/js9 in <module>()
----> 1 task.wait(die=True)

/opt/code/github/zero-os/0-robot/zerorobot/task/task.py in wait(self, timeout, die)
    129                 logger.critical('task is in error state, but no eco')
    130             else:
--> 131                 raise self.eco
    132 
    133         return self

ErrorConditionObject: failed to detect a valid IP address from 'cluster01'

```

**Comment by BolaNasr** [comment]
https://github.com/threefoldtech/jumpscale_lib/pull/63

**Comment by islamTaha12** [comment]
https://github.com/threefoldtech/jumpscale_lib/issues/68
