### ISSUE TITLE
Directory: error when loading home page

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/jumpscale_lib#300]
```
[2019-06-17 07:50:43,873] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/code/github/threefoldtech/jumpscale_lib/JumpscaleLib/servers/grid_capacity/server/frontend_blueprint.py", line 18, in capacity
    countries = NodeRegistration.all_countries()
  File "/opt/code/github/threefoldtech/jumpscale_lib/JumpscaleLib/servers/grid_capacity/server/models.py", line 102, in all_countries
    for cap in capacities:
  File "/usr/local/lib/python3.5/dist-packages/mongoengine/queryset/queryset.py", line 99, in _iter_results
    self._populate_cache()
  File "/usr/local/lib/python3.5/dist-packages/mongoengine/queryset/queryset.py", line 118, in _populate_cache
    self._result_cache.append(next(self))
  File "/usr/local/lib/python3.5/dist-packages/mongoengine/queryset/base.py", line 1486, in __next__
    raw_doc = next(self._cursor)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/cursor.py", line 1189, in next
    if len(self.__data) or self._refresh():
  File "/usr/local/lib/python3.5/dist-packages/pymongo/cursor.py", line 1104, in _refresh
    self.__send_message(q)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/cursor.py", line 982, in __send_message
    helpers._check_command_response(first)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/helpers.py", line 155, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: Executor error during find command :: caused by :: errmsg: "Sort operation used more than the maximum 33554432 bytes of RAM. Add an index, or specify a smaller limit."
172.19.0.12 - - [17/Jun/2019 07:50:43] "GET / HTTP/1.1" 500 -
```

**Comment by zaibon** [comment]
fixed in https://github.com/threefoldtech/jumpscale_lib/commit/aa1b0859d7ccfea4f4e89bb0d3ed2a8e18fb2825
