### ISSUE TITLE
delete storagepool device doesn't clean up correctly

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/jumpscale_lib#35]
*Issue migrated from [https://api.github.com/repos/Jumpscale/lib9/issues/318](), opened by @Dinaamagdy*

## Steps 
- boot cpu-1 on be scale 2 with ```http://unsecure.bootstrap.gig.tech/krn/development/8850338390f481e6/development```
## Issue
 Check the zrobot server return the following error : 
```
ERROR:service-205f4241-6001-473d-a631-dea8d7327ac2:error executing action _monitor:
Traceback (most recent call last):
  File "/opt/code/github/zero-os/0-robot/zerorobot/task/task.py", line 79, in execute
    self._result = self._func()
  File "/opt/code/github/zero-os/0-templates/templates/node/node.py", line 51, in _monitor
    sp = self.node_sal.storagepools.get('zos-cache')
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/zero_os/sal/StoragePool.py", line 70, in get
    raise ValueError("Could not find StoragePool with name {}".format(name))
ValueError: Could not find StoragePool with name zos-cache
```
but when you check from the node you get the following error : 
 btrfs filesystem show --raw
```
warning, device 2 is missing
Label: 'ROOT'  uuid: b8049c50-f0a4-4d6b-b6dc-6523ff577e26
  Total devices 2 FS bytes used 42279981056
  devid    1 size 42949672960 used 42949672960 path /dev/sda4
  *** Some devices missing
```

**Comment by rkhamis** [comment]
*commented by @zaibon
has been solved: https://github.com/zero-os/0-core/issues/692 
setting this one to verification*

**Comment by hossnys** [comment]
verified on zero-os development  branch

**Comment by hossnys** [comment]
steps of verifying :
- creating zos vm with two additional disks on it .
- make  btrfs group for this two disks
 ```mkfs.btrfs /dev/sdb /dev/sdc```
- ruined one of these two disks using this :
``` dd if /dev/zero of /dev/sdc count=500M bs=1024
- then try to show btrfs to watch is there proper output or no:
``` node_client.bash("btrfs filesystem show").get()
Out[76]: 
STATE: 0 SUCCESS
STDOUT:
Label: 'sp_zos-cache'  uuid: 6dcc31ad-20a8-4271-b582-85a8c16e0190
  Total devices 1 FS bytes used 80.05MiB
  devid    1 size 5.00GiB used 1.02GiB path /dev/sdb1

warning, device 1 is missing
Label: none  uuid: 1aa9be28-fb55-43a6-91ff-ac2f7b53ade3
  Total devices 2 FS bytes used 112.00KiB
  devid    2 size 20.00GiB used 2.01GiB path /dev/sdc
  *** Some devices missing
```

**Comment by hossnys** [comment]
after deleting the partition found this error on the z-robot logs 
![screenshot from 2018-08-14 12-59-03](https://user-images.githubusercontent.com/26298009/44088142-5abe8236-9fc2-11e8-81e6-f38d5d8b1c40.png)
